---
openapi: 3.1.1
info:
  title: API Conseillers-Entreprises V1
  description: "## Bienvenue sur la documentation de l’API de conseillers-entreprises.service-public.fr\n
    \       \nCette API permet à une organisation de proposer un formulaire de dépôt
    de besoin d'entreprise connecté à Conseillers-entreprises.service-public.fr sur
    son propre site internet.\n        \nConcrètement, cette API permet de :\n        \n-
    récupérer la liste des pages d'atterrisage, thèmes et sujets autorisés pour l'organisation
    concernée,\n        \n- d'envoyer à Conseillers-entreprises.service-public.fr
    un besoin\n        \n### Limite des requêtes\n        \nLe serveur accepte un
    maximum de 300 appels par 5 minutes.\n        "
  version: 1.0.0
  contact:
    name: Équipe technique
    email: tech@entreprises.service-public.fr
tags:
- name: Page d’atterrissage
- name: Thèmes
- name: Sujets
paths:
  "/api/v1/landings/{landing_id}/landing_subjects":
    get:
      summary: Liste des sujets
      tags:
      - Sujets
      description: Affiche tous les sujets d’une page d’atterrissage
      operationId: listLandingSubjects
      parameters:
      - name: landing_id
        in: path
        description: identifiant de la page d’atterrissage
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: ok
          content:
            application/json:
              examples:
                test_example:
                  value:
                    data:
                    - id: 297
                      title: Recruter un ou plusieurs salariés
                      slug: recruter
                      landing_id: 297
                      landing_theme_id: 309
                      landing_theme_slug: recrutement-formation
                      description: "<ul><li>S’informer sur les aides à l'embauche
                        des jeunes, à l'apprentissage</li><li>S'informer sur les emplois
                        francs en quartiers prioritaires, le contrat de professionnalisation,
                        le VTE Vert sur les métiers de la transition écologique</li><li>Trouver
                        des candidats</li></ul>"
                      description_explanation: "<ul><li>le type de poste</li><li>si
                        l'offre est déjà connue de Pôle emploi</li><li>si vous envisagez
                        de recruter une personne en situation de handicap</li></ul>"
                      requires_siret: true
                      requires_location: false
                      questions_additionnelles:
                      - id: 91
                        key: recrutement_poste_cadre
                        position: 1
                        question: Recrutez-vous sur un poste d’ingénieur, de manager
                          ou de niveau Bac +3 ?
                        question_type: boolean
                      - id: 92
                        key: recrutement_en_apprentissage
                        position: 2
                        question: Recrutez-vous un apprenti ou un stagiaire ?
                        question_type: boolean
                      institutions_partenaires:
                      - Chambre de Commerce et d'Industrie (CCI)
                    - id: 298
                      title: Mettre en place un projet de formation
                      slug: former
                      landing_id: 297
                      landing_theme_id: 309
                      landing_theme_slug: recrutement-formation
                      description: "<ul><li>Choisir la bonne formation</li><li>Trouver
                        votre OPCO, financer la formation</li><li>Mettre en place
                        un plan de formation entreprise</li><li>Se former en tant
                        que chef d'entreprise</li><li>Former vos salariés en activité
                        partielle grâce au FNE formation</li></ul>"
                      description_explanation: "<ul><li>votre activité</li><li>combien
                        de salariés vous souhaitez former</li><li>sur quelles thématiques</li><li>dans
                        quel but</li></ul>"
                      requires_siret: true
                      requires_location: false
                      questions_additionnelles: []
                      institutions_partenaires: []
                    metadata:
                      total_results: 2
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/landing_subject"
                  metadata:
                    type: object
                    properties:
                      total_results:
                        type: integer
                        description: Nombre de sujets de la page d’atterrissage.
  "/api/v1/landings/{landing_id}/landing_subjects/search":
    get:
      summary: Recherche d’un sujet à partir de son slug
      tags:
      - Sujets
      description: Recherche d’un sujet à partir de son slug, équivalent à un mot
        clé, pour faciliter la récupération d’un sujet spécifique.
      operationId: searchLandingSubject
      parameters:
      - name: landing_id
        in: path
        description: identifiant de la page d’atterrissage
        required: true
        schema:
          type: integer
      - name: slug
        in: query
        description: Slug du sujet
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Sujet trouvé
          content:
            application/json:
              examples:
                test_example:
                  value:
                    data:
                      id: 300
                      title: Recruter un ou plusieurs salariés
                      slug: recruter
                      landing_id: 299
                      landing_theme_id: 311
                      landing_theme_slug: recrutement-formation
                      description: "<ul><li>S’informer sur les aides à l'embauche
                        des jeunes, à l'apprentissage</li><li>S'informer sur les emplois
                        francs en quartiers prioritaires, le contrat de professionnalisation,
                        le VTE Vert sur les métiers de la transition écologique</li><li>Trouver
                        des candidats</li></ul>"
                      description_explanation: "<ul><li>le type de poste</li><li>si
                        l'offre est déjà connue de Pôle emploi</li><li>si vous envisagez
                        de recruter une personne en situation de handicap</li></ul>"
                      requires_siret: true
                      requires_location: false
                      questions_additionnelles:
                      - id: 93
                        key: recrutement_poste_cadre
                        position: 1
                        question: Recrutez-vous sur un poste d’ingénieur, de manager
                          ou de niveau Bac +3 ?
                        question_type: boolean
                      - id: 94
                        key: recrutement_en_apprentissage
                        position: 2
                        question: Recrutez-vous un apprenti ou un stagiaire ?
                        question_type: boolean
                      institutions_partenaires:
                      - Chambre de Commerce et d'Industrie (CCI)
              schema:
                type: object
                properties:
                  data:
                    "$ref": "#/components/schemas/landing_subject"
                  metadata:
                    type: object
        '404':
          description: Page d’atterrissage inconnue
          content:
            application/json:
              examples:
                test_example:
                  value:
                    errors:
                    - source: Sujet de landing
                      message: n’existe pas ou est invalide
              schema:
                errors:
                  type: array
                  items:
                    "$ref": "#/components/schemas/error"
        '400':
          description: Paramètres vides
          content:
            application/json:
              examples:
                test_example:
                  value:
                    errors:
                    - source: paramètres de requête
                      message: malformés ou inconnus
              schema:
                errors:
                  type: array
                  items:
                    "$ref": "#/components/schemas/error"
  "/api/v1/landings/{landing_id}/landing_subjects/{id}":
    get:
      summary: Page sujet
      tags:
      - Sujets
      description: Affiche le détail d’un formulaire sujet
      operationId: showLandingSubject
      parameters:
      - name: landing_id
        in: path
        description: identifiant de la page d’atterrissage
        required: true
        schema:
          type: integer
      - name: id
        in: path
        description: identifiant du sujet
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Sujet trouvé
          content:
            application/json:
              examples:
                test_example:
                  value:
                    data:
                      id: 306
                      title: Recruter un ou plusieurs salariés
                      slug: recruter
                      landing_id: 302
                      landing_theme_id: 314
                      landing_theme_slug: recrutement-formation
                      description: "<ul><li>S’informer sur les aides à l'embauche
                        des jeunes, à l'apprentissage</li><li>S'informer sur les emplois
                        francs en quartiers prioritaires, le contrat de professionnalisation,
                        le VTE Vert sur les métiers de la transition écologique</li><li>Trouver
                        des candidats</li></ul>"
                      description_explanation: "<ul><li>le type de poste</li><li>si
                        l'offre est déjà connue de Pôle emploi</li><li>si vous envisagez
                        de recruter une personne en situation de handicap</li></ul>"
                      requires_siret: true
                      requires_location: false
                      questions_additionnelles:
                      - id: 99
                        key: recrutement_poste_cadre
                        position: 1
                        question: Recrutez-vous sur un poste d’ingénieur, de manager
                          ou de niveau Bac +3 ?
                        question_type: boolean
                      - id: 100
                        key: recrutement_en_apprentissage
                        position: 2
                        question: Recrutez-vous un apprenti ou un stagiaire ?
                        question_type: boolean
                      institutions_partenaires:
                      - Chambre de Commerce et d'Industrie (CCI)
                      - OPérateur de COmpétences (OPCO)
              schema:
                type: object
                properties:
                  data:
                    "$ref": "#/components/schemas/landing_subject"
                  metadata:
                    type: object
  "/api/v1/landings/{landing_id}/landing_themes":
    get:
      summary: Liste des thèmes
      tags:
      - Thèmes
      description: Affiche tous les thèmes pour l’organisation authentifiée
      operationId: listLandingThemes
      parameters:
      - name: landing_id
        in: path
        description: identifiant de la page d’atterrissage
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: ok
          content:
            application/json:
              examples:
                test_example:
                  value:
                    data:
                    - id: 315
                      title: Environnement, transition écologique & RSE
                      slug: environnement-transition-ecologique
                      description: Optimiser vos consommations d’énergie, valoriser
                        vos déchets par la revente de matière, éco-concevoir un produit,
                        mettre en place une démarche RSE, un plan de déplacement entreprise
                        (PDE).
                      landing_subjects:
                      - id: 308
                        title: Traitement et valorisation des déchets
                        slug: dechets
                        landing_id: 303
                        landing_theme_id: 315
                        landing_theme_slug: environnement-transition-ecologique
                        description: "<ul><li>Optimiser votre tri sélectif en entreprise</li><li>Réduire
                          vos déchets</li><li>Valoriser la revente de matières, trouver
                          de nouveaux débouchés</li></ul>"
                        description_explanation: "<ul><li>quelle est concrètement
                          votre activité</li><li>ce que votre projet apporte à votre
                          entreprise</li><li>quel accompagnement vous souhaitez (réflexion
                          stratégique, appui technique ou appui à la mise en oeuvre)</li></ul>"
                        requires_siret: true
                        requires_location: false
                      - id: 309
                        title: Gestion de l’eau
                        slug: eau
                        landing_id: 303
                        landing_theme_id: 315
                        landing_theme_slug: environnement-transition-ecologique
                        description: "<ul><li>Réduire vos consommations d’eau</li><li>Dimensionner
                          la récupération d’eau pluviale</li><li>Maintenir de la biodiversité
                          sur votre territoire</li></ul>"
                        description_explanation: "<ul><li>quelle est concrètement
                          votre activité</li><li>si vous utilisez de l’eau dans votre
                          process de fabrication</li><li>ce que votre projet apporte
                          à votre entreprise</li><li>quel accompagnement vous souhaitez
                          (réflexion stratégique, appui technique ou appui à la mise
                          en oeuvre)</li></ul>"
                        requires_siret: true
                        requires_location: false
                    - id: 317
                      title: Recruter ou former vos salariés, améliorer l’organisation
                        du travail
                      slug: recrutement-formation
                      description: S’informer sur les aides à l’embauche, trouver
                        des candidats, recruter un travailleur handicapé, identifier
                        la bonne formation, être accompagné sur la GPEC, gérer les
                        départs en retraite.
                      landing_subjects: []
                    metadata:
                      total_results: 2
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/landing_theme"
                  metadata:
                    type: object
                    properties:
                      total_results:
                        type: integer
                        description: Nombre de thèmes pour l’organisation authentifiée.
  "/api/v1/landings/{landing_id}/landing_themes/{id}":
    get:
      summary: Page thème
      tags:
      - Thèmes
      description: Affiche le détail d’un thème et la liste de ses sujets
      operationId: showLandingTheme
      parameters:
      - name: landing_id
        in: path
        description: identifiant de la page d’atterrissage
        required: true
        schema:
          type: integer
      - name: id
        in: path
        description: identifiant du thème
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Page thème trouvée
          content:
            application/json:
              examples:
                test_example:
                  value:
                    data:
                      id: 320
                      title: Environnement, transition écologique & RSE
                      slug: environnement-transition-ecologique
                      description: Optimiser vos consommations d’énergie, valoriser
                        vos déchets par la revente de matière, éco-concevoir un produit,
                        mettre en place une démarche RSE, un plan de déplacement entreprise
                        (PDE).
                      landing_subjects:
                      - id: 314
                        title: Traitement et valorisation des déchets
                        slug: dechets
                        landing_id: 306
                        landing_theme_id: 320
                        landing_theme_slug: environnement-transition-ecologique
                        description: "<ul><li>Optimiser votre tri sélectif en entreprise</li><li>Réduire
                          vos déchets</li><li>Valoriser la revente de matières, trouver
                          de nouveaux débouchés</li></ul>"
                        description_explanation: "<ul><li>quelle est concrètement
                          votre activité</li><li>ce que votre projet apporte à votre
                          entreprise</li><li>quel accompagnement vous souhaitez (réflexion
                          stratégique, appui technique ou appui à la mise en oeuvre)</li></ul>"
                        requires_siret: true
                        requires_location: false
                      - id: 315
                        title: Gestion de l’eau
                        slug: eau
                        landing_id: 306
                        landing_theme_id: 320
                        landing_theme_slug: environnement-transition-ecologique
                        description: "<ul><li>Réduire vos consommations d’eau</li><li>Dimensionner
                          la récupération d’eau pluviale</li><li>Maintenir de la biodiversité
                          sur votre territoire</li></ul>"
                        description_explanation: "<ul><li>quelle est concrètement
                          votre activité</li><li>si vous utilisez de l’eau dans votre
                          process de fabrication</li><li>ce que votre projet apporte
                          à votre entreprise</li><li>quel accompagnement vous souhaitez
                          (réflexion stratégique, appui technique ou appui à la mise
                          en oeuvre)</li></ul>"
                        requires_siret: true
                        requires_location: false
                    metadata:
                      total_subjects: 2
              schema:
                type: object
                properties:
                  data:
                    "$ref": "#/components/schemas/landing_theme"
                  metadata:
                    type: object
                    properties:
                      total_themes:
                        type: integer
                        description: Nombre de sujets liés aux thèmes.
  "/api/v1/landings":
    get:
      summary: Liste des pages d’atterrissage
      tags:
      - Page d’atterrissage
      description: Affiche toutes les pages d’atterrissage pour l’organisation authentifiée
      operationId: listLandings
      responses:
        '200':
          description: ok
          content:
            application/json:
              examples:
                test_example:
                  value:
                    data:
                    - id: 307
                      title: Page d’atterrissage 01
                      slug: page-atterrissage-01
                      partner_url: https://hirthe-raynor.example
                      landing_themes:
                      - id: 321
                        title: Environnement, transition écologique & RSE
                        slug: environnement-transition-ecologique
                        description: Optimiser vos consommations d’énergie, valoriser
                          vos déchets par la revente de matière, éco-concevoir un
                          produit, mettre en place une démarche RSE, un plan de déplacement
                          entreprise (PDE).
                      - id: 322
                        title: Améliorer la santé et la sécurité au travail
                        slug: sante-securite-travail
                        description: Réviser votre document unique d’évaluation des
                          risques professionnels, former vos salariés à la prévention
                          des risques professionnels (DUERP), connaître les règles
                          d’hygiène, améliorer la qualité de vie au travail pour être
                          plus performant.
                    metadata:
                      total_results: 1
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/landing"
                  metadata:
                    type: object
                    properties:
                      total_results:
                        type: integer
                        description: Nombre de pages d’atterrissage pour l’organisation
                          authentifiée.
        '404':
          description: Mauvais token
          content:
            application/json:
              examples:
                test_example:
                  value:
                    errors:
                    - source: Token d’API
                      message: n’existe pas ou est invalide
              schema:
                errors:
                  type: array
                  items:
                    "$ref": "#/components/schemas/error"
  "/api/v1/landings/search":
    get:
      summary: Recherche d’une page d’atterrissage à partir de l’url de sa page d’appel
      tags:
      - Page d’atterrissage
      description: Afin de pouvoir tracer et quantifier les appels, nous enregistrons
        les url des pages des sites partenaires depuis lesquelles l’API est appelé.
        Ainsi, pour retrouver la page d’atterrissage devant figurer à l’url XX, vous
        pouvez faire une recherche via cette url.
      operationId: searchLandings
      parameters:
      - name: url
        in: query
        description: Domaine du site qui appelle l’API
        required: false
        schema:
          type: string
      responses:
        '200':
          description: Pages d’atterrissage trouvées
          content:
            application/json:
              examples:
                test_example:
                  value:
                    data:
                    - id: 311
                      title: Page d’atterrissage 01
                      slug: page-atterrissage-01
                      partner_url: https://tremblay.test
                      landing_themes:
                      - id: 327
                        title: Environnement, transition écologique & RSE
                        slug: environnement-transition-ecologique
                        description: Optimiser vos consommations d’énergie, valoriser
                          vos déchets par la revente de matière, éco-concevoir un
                          produit, mettre en place une démarche RSE, un plan de déplacement
                          entreprise (PDE).
                      - id: 328
                        title: Améliorer la santé et la sécurité au travail
                        slug: sante-securite-travail
                        description: Réviser votre document unique d’évaluation des
                          risques professionnels, former vos salariés à la prévention
                          des risques professionnels (DUERP), connaître les règles
                          d’hygiène, améliorer la qualité de vie au travail pour être
                          plus performant.
                    metadata:
                      total_results: 1
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/landing"
                  metadata:
                    type: object
                    properties:
                      total_results:
                        type: integer
                        description: Nombre de pages d’atterrissage pour l’organisation
                          authentifiée.
        '404':
          description: Page d’atterrissage inconnue
          content:
            application/json:
              examples:
                test_example:
                  value:
                    errors:
                    - source: Coopération
                      message: n’existe pas ou est invalide
              schema:
                errors:
                  type: array
                  items:
                    "$ref": "#/components/schemas/error"
        '400':
          description: Paramètres vides
          content:
            application/json:
              examples:
                test_example:
                  value:
                    errors:
                    - source: paramètres de requête
                      message: malformés ou inconnus
              schema:
                errors:
                  type: array
                  items:
                    "$ref": "#/components/schemas/error"
  "/api/v1/landings/{id}":
    get:
      summary: Page d’atterrissage
      tags:
      - Page d’atterrissage
      description: Affiche le détail d’une page d’atterrissage et la liste de ses
        thèmes
      operationId: showLanding
      parameters:
      - name: id
        in: path
        description: identifiant de la page
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Page d’atterrissage trouvée
          content:
            application/json:
              examples:
                test_example:
                  value:
                    data:
                      id: 314
                      title: Page d’atterrissage 01
                      slug: page-atterrissage-01
                      partner_url: https://osinski-anderson.test
                      landing_themes:
                      - id: 333
                        title: Environnement, transition écologique & RSE
                        slug: environnement-transition-ecologique
                        description: Optimiser vos consommations d’énergie, valoriser
                          vos déchets par la revente de matière, éco-concevoir un
                          produit, mettre en place une démarche RSE, un plan de déplacement
                          entreprise (PDE).
                      - id: 334
                        title: Améliorer la santé et la sécurité au travail
                        slug: sante-securite-travail
                        description: Réviser votre document unique d’évaluation des
                          risques professionnels, former vos salariés à la prévention
                          des risques professionnels (DUERP), connaître les règles
                          d’hygiène, améliorer la qualité de vie au travail pour être
                          plus performant.
                    metadata:
                      total_themes: 2
              schema:
                type: object
                properties:
                  data:
                    "$ref": "#/components/schemas/landing"
                  metadata:
                    type: object
                    properties:
                      total_themes:
                        type: integer
                        description: Nombre de thèmes liée à la page d’atterrissage.
  "/api/v1/solicitations":
    post:
      summary: Créer une sollicitation
      tags:
      - Sollicitation
      description: Crée une sollicitation liée à un sujet, en provenance d’une institution.
      operationId: createSolicitation
      parameters: []
      responses:
        '200':
          description: Solicitation créée
          content:
            application/json:
              examples:
                solicitation_creee:
                  value:
                    data:
                      institutions_partenaires:
                      - Chambre de Commerce et d'Industrie (CCI)
                      - OPérateur de COmpétences (OPCO)
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      "$ref": "#/components/schemas/solicitation_created"
        '400':
          description: Paramètre "Solicitation" manquant
          content:
            application/json:
              examples:
                parametre_solicitation_manquant:
                  value:
                    errors:
                    - source: solicitation
                      message: le paramètre est manquant
              schema:
                errors:
                  type: array
                  items:
                    "$ref": "#/components/schemas/error"
        '422':
          description: Page introuvable
          content:
            application/json:
              examples:
                url_d_origine_manquante:
                  value:
                    errors:
                    - source: Url page d’origine
                      message: doit être rempli(e)
                siret_invalide:
                  value:
                    errors:
                    - source: SIRET
                      message: doit être un numéro à 14 chiffres valide
                un_champs_obligatoire_de_la_solicitation_manquant:
                  value:
                    errors:
                    - source: Questions additionnelles
                      message: doit être rempli(e)
                    - source: Questions additionnelles
                      message: doivent correspondre aux questions du sujet de la demande
                solicitation_creee_meme_avec_de_mauvais_id_de_questions_additionnelles:
                  value:
                    errors:
                    - source: Questions additionnelles
                      message: doivent correspondre aux questions du sujet de la demande
                page_introuvable:
                  value:
                    errors:
                    - source: Page d’atterrissage
                      message: doit être rempli(e)
              schema:
                errors:
                  type: array
                  items:
                    "$ref": "#/components/schemas/error"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/new_solicitation"
        required: true
servers:
- url: https://conseillers-entreprises.clairezuliani.fr
- url: https://ce-staging.osc-fr1.scalingo.io
components:
  schemas:
    landing:
      type: object
      properties:
        id:
          type: integer
        iframe_category:
          type: string
        title:
          type: string
        slug:
          type: string
        partner_url:
          type: string
        landing_themes:
          type: array
          items:
            "$ref": "#/components/schemas/landing_theme"
      required:
      - id
      - title
      - partner_url
    landing_theme:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        slug:
          type: string
        description:
          type: string
        landing_subjects:
          type: array
          items:
            "$ref": "#/components/schemas/landing_subject"
      required:
      - id
      - title
    landing_subject:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        slug:
          type: string
        description:
          type: string
        description_explanation:
          type: string
        requires_siret:
          type: boolean
        requires_location:
          type: boolean
        landing_subjects:
          type: array
          items:
            "$ref": "#/components/schemas/landing_subject"
      required:
      - id
      - title
      - slug
    new_solicitation:
      type: object
      properties:
        solicitation:
          type: object
          properties:
            landing_id:
              type: integer
            landing_subject_id:
              type: integer
            description:
              type: string
            full_name:
              type: string
            email:
              type: string
            phone_number:
              type: string
            siret:
              type: string
            location:
              type: string
            origin_url:
              type: string
            questions_additionnelles:
              type: array
              items:
                "$ref": "#/components/schemas/question_additionnelle_short"
          required:
          - landing_id
          - landing_subject_id
          - description
          - full_name
          - email
          - origin_url
      required:
      - solicitation
    solicitation_created:
      type: object
      properties:
        uuid:
          type: string
        landing_subject:
          type: string
        full_name:
          type: string
        email:
          type: string
        phone_number:
          type: string
        siret:
          type: string
        location:
          type: string
        description:
          type: string
        code_region:
          type: integer
        status:
          type: string
        questions_additionnelles:
          type: array
          items:
            "$ref": "#/components/schemas/question_additionnelle_long"
        origin_url:
          type: string
      required:
      - landing_id
      - landing_subject_id
      - description
      - full_name
      - email
      - origin_url
    question_additionnelle_short:
      type: object
      properties:
        question_id:
          type: integer
        answer:
          type: boolean
    question_additionnelle_long:
      type: object
      properties:
        question_id:
          type: integer
        question_label:
          type: string
        answer:
          type: boolean
    error:
      type: object
      properties:
        source:
          type: string
        message:
          type: string
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      description: "Le jeton vous est fourni après étude de votre demande par Conseillers-entreprises.service-public.fr.\n
        \           \nIl doit être placé dans le header '`Authorization: Bearer VOTRE_JETON`'.\n
        \           \nSa validité est de 18 mois, renouvelable sur demande."
security:
- bearer_auth: []
